version: "3.7"
services:

  detector:
    image: coral
    container_name: detector
    devices:
      - /dev/apex_0:/dev/apex_0 o 
    environment:
      - TZ=America/Los_Angles
    volumes:
      - /home/mischa/git/coral_object_detector:/python
    restart: always
    privileged: true

  detector-web:
    image: detector-web
    container_name: detector-web
    volumes:
      - /home/mischa/git/coral_object_detector:/python
    ports:
      - 8001:8001
    restart: always

volumes:
  localstorage:
